export type { Professional, ProfessionalSettings, PlanType, ProfessionType } from "./types/professional";
export type {
  Client,
  JourneyStage,
  ClientGender,
  ClientSource,
  CreateClientManualInput,
  CreateClientManualOutput,
  MoveClientStageInput,
  MoveClientStageOutput,
} from "./types/client";
export type { TeamMember, NivelAcesso } from "./types/team-member";
export type { UserRole, UserRoleRecord } from "./types/user-role";
export type {
  Service,
  ServiceCategory,
  CreateServiceInput,
  UpdateServiceInput,
  ServiceMutationOutput,
  DeactivateServiceOutput,
} from "./types/service";
export type {
  Appointment,
  AppointmentStatus,
  AppointmentSource,
  AppointmentOutcome,
  AppointmentSeriesFrequency,
  CreateAppointmentInput,
  CreateAppointmentOutput,
  CreateAppointmentSeriesInput,
  CreateAppointmentSeriesOutput,
  CancelAppointmentInput,
  CancelAppointmentSeriesInput,
  CancelAppointmentSeriesOutput,
  AppointmentStatusOutput,
  RegisterAppointmentOutcomeInput,
} from "./types/appointment";
export type { Session, RegisterSessionInput, RegisterSessionOutput } from "./types/session";
export type {
  DashboardAppointment,
  DashboardAttentionItem,
  DashboardPulse,
  DashboardSummary,
} from "./types/dashboard";
export type {
  ProfessionalReports,
  ReportsOccupancySlot,
  ReportsServiceRanking,
  ReportsSummary,
  ReportsTopClient,
} from "./types/reports";
export type {
  FinancialPaymentMethod,
  FinancialSummary,
  FinancialTransaction,
  FinancialTransactionStatus,
  FinancialTransactionType,
  FinancialTransactionWithClient,
  FinanceBankAccount,
  FinanceCategory,
  FinanceCostCenter,
  FinanceGatewaySetting,
  FinanceSettings,
  Product,
  CreateFinancialTransactionInput,
  CreateFinancialTransactionOutput,
  CreatePosSaleInput,
  CreatePosSaleOutput,
  ImportReconciliationInput,
  MarkTransactionPaidInput,
  MarkTransactionPaidOutput,
  PosSaleItemInput,
  ReconciliationItem,
  CancelFinancialTransactionInput,
  CancelFinancialTransactionOutput,
  ApproveBillingCollectionOutput,
} from "./types/financial";

export type {
  CloseFunnelOpportunityInput,
  CloseFunnelOpportunityOutput,
  CreateFunnelOpportunityInput,
  CreateFunnelOpportunityOutput,
  FunnelBoard,
  FunnelEvent,
  FunnelEventType,
  FunnelOpportunity,
  FunnelOpportunitySource,
  FunnelOpportunityStatus,
  FunnelStage,
  LogFunnelActivityInput,
  LogFunnelActivityOutput,
  MoveFunnelOpportunityInput,
  MoveFunnelOpportunityOutput,
  SalesFunnel,
} from "./types/funnel";

export type {
  WhatsAppMessageReceivedEvent,
  WhatsAppInstanceConnectedEvent,
  WhatsAppInstanceDisconnectedEvent,
} from "./types/whatsapp-events";

export type {
  AnamneseTemplate,
  ClientPackage,
  ClientPackageStatus,
  ClientPackageWithDetails,
  Contract,
  ContractStatus,
  ContractWithClient,
  CreateContractFromModeloInput,
  CreateContractOutput,
  CreateModeloInput,
  CreateModeloOutput,
  CreateQuoteInput,
  CreateQuoteOutput,
  CreateServicePackageInput,
  CreateServicePackageOutput,
  MarkContractSignedManualOutput,
  Modelo,
  ModeloType,
  PackageSessionUsage,
  Quote,
  QuoteItem,
  QuoteStatus,
  QuoteWithClient,
  SellClientPackageInput,
  SellClientPackageOutput,
  SendQuoteDryRunOutput,
  SendQuoteForApprovalOutput,
  ConvertApprovedQuoteOutput,
  ServicePackage,
  ServicePackageWithService,
  UpdateAnamneseTemplateInput,
  UpdateAnamneseTemplateOutput,
  UseClientPackageSessionInput,
  UseClientPackageSessionOutput,
} from "./types/documents-packages";
